name: Run test
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 16]
        app: [1.0.0, 2.0.0]
    steps:
      - name: Get Repo
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ matrix.app }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name : Install deps
        run: npm install
      - name: Run test
        run: npm run test
      - name: download
        uses: actions/upload-artifact@v3
        with:
          name: Download Test Artifact
          path: ./reports/
  covers:
    needs: [tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 16]
        app: [1.0.0, 2.0.0]
    steps:
      - name: Get Repo
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ matrix.app }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name : Install deps
        run: npm install
      - name: Run cover
        run: npm run test
      - name: download
        uses: actions/upload-artifact@v3
        with:
          name: Download Cover Artifact
          path: ./reports/