name: Run test
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name : Install deps
        run: npm install
      - name: Run test
        run: npm run test
      - name: Run test cover
        run: npm run cover
      - name: download
        uses: actions/upload-artifact@v3
        with:
          name: Download Test Artifact
          path: ./reports/
  deploy-docker:
    needs: [tests, covers]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: dl3c01n/node-test
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}