name: Run test
on: [push]
strategy:
  matrix:
    node: [10, 12, 14, 16]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name : Install deps
        - run: npm install
      - name: Run test
        - run: npm run test